### ISSUE TITLE
Provide a Searcher for script templates

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-search#1]
In addition to snippets, it might be useful to be able to search all available script templates and open them in the script editor.

See also https://github.com/scijava/script-editor/issues/6.

**Comment by imagejan** [comment]
I've made a first attempt implementing this on the [`add-template-search` branch](https://github.com/scijava/scijava-search/compare/add-template-search).

Remaining tasks:

* [ ] Open the script when the *Open* button is pressed. (@ctrueden what's the preferred way of doing so using a SciJava service? We should keep it agnostic of the `script-editor` component, no?)

On the other hand, maybe this whole search module should actually live in the `script-editor` repo? Opinions, @ctrueden, @stelfrich?

**Comment by stelfrich** [comment]
> On the other hand, maybe this whole search module should actually live in the `script-editor` repo?

That's a philosophical question, I guess. Templates, in general, are independent of the `script-editor` component. If `script-editor` is not available, there's not really that much you can do with the search result, right? However, you should still be able to get template search results, even if you can't take any action on them in the previous case.

What about keeping `TemplateSearchResult` and `TemplateSearcher` in here and moving `OpenTemplateSearchActionFactory` to `script-editor`? We don't have an example for that kind of separation at the moment, but generating search results and providing an action could be separated.

**Comment by imagejan** [comment]
Thanks, @stelfrich, for the advice. I wasn't aware that the "Source" and "Help" `SearchActionFactory` classes already live in `imagej-legacy`.

I now moved `OpenTemplateSearchActionFactory` to `imagej-legacy` in https://github.com/imagej/imagej-legacy/pull/181.
