### ISSUE TITLE
SourceFinder returns wrong URLs for original ImageJ classes

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-search#22]
Since the deprecation of ImageJA and the changes to `imagej/ImageJ` to be able to build with Maven, the <kbd>Source</kbd> button returns a `404` page for all original ImageJ menu items (i.e. all `ij.*` classes).

I guess that we'd somehow teach [`SourceFinder`](https://github.com/scijava/scijava-search/blob/70a8156e7cb65a3306a5dd6d92c9e07d9c70a1f0/src/main/java/org/scijava/search/SourceFinder.java) to respect these lines in the target POM:

```xml
				<artifactId>maven-source-plugin</artifactId>
				<configuration>
					<includes>ij/**</includes>
				</configuration>
```

https://github.com/imagej/ImageJ/blob/eb466f8a0a73a1f9bffec19bd9b3176d220a8896/pom.xml#L200-L203

/cc @ctrueden @hinerm

**Comment by ctrueden** [comment]
Thanks for the heads up, @imagejan. The primary line of concern is this one:

https://github.com/imagej/ImageJ/blob/eb466f8a0a73a1f9bffec19bd9b3176d220a8896/pom.xml#L112

We can just check the POM for a `sourceDirectory` under `properties`, and use that instead of `src/main/java` if present.

**Comment by imagejan** [comment]
@ctrueden thanks for the pointers.

`pom.cdata("//build/sourceDirectory")` for the `ij` artifact returns `${project.basedir}` literally. Do you have a suggestion how I get at the property value?

**Comment by ctrueden** [comment]
I don't believe `basedir` is something anyone can or should be overriding in their POM. Therefore, `${project.basedir}` can always be treated as `/` (or empty string, depending exactly how things are coded) for the GitHub repository path prefix—at least for single-module projects. (We can worry about multi-module projects some day later, but if you want to be thorough, the only one we have currently is https://github.com/axtimwalde/mpicbg.)
