### ISSUE TITLE
ClassesSearcher sometimes returns no results

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava-search#25]
On some systems, the `ClassesSearcher` seems to return no results. @JenuC and I saw this first on his Windows 10 machine, and I was able to replicate with @ctrueden yesterday on a shared Windows 10 workstation.

However, I *cannot* replicate today on that same shared workstation. I am now testing on my own account and a fresh Fiji installation, whereas yesterday @ctrueden and I tested on his account with an existing Fiji installation. :exploding_head:

**Comment by JenuC** [comment]
ClassesSearcher seems to work after the Fiji update (on my machine). :thumbsup:

**Comment by gselzer** [comment]
That's good to hear!

@ctrueden I'm going to close this, we can always reopen it if you (or someone else) can replicate.
